In [ ]:
# importing numpy library
import numpy as np

In [ ]:
# create numpy 2d-array
m = np.array([[1, 2],
			[2, 3]])

print("Printing the Original square array:\n",m)
print()
print('***************************************')
print()
# finding eigenvalues and eigenvectors
w, v = np.linalg.eig(m)

Printing the Original square array:
 [[1 2]
 [2 3]]

***************************************



In [ ]:
# printing eigen values
print("Printing the Eigen values of the given square array:\n",w)
print()
# printing eigen vectors
print("Printing Right Eigen Vectors of the given square array:\n",v)

Printing the Eigen values of the given square array:
 [-0.23606798  4.23606798]

Printing Right Eigen Vectors of the given square array:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [ ]:
# importing numpy library
import numpy as np

In [ ]:
# create numpy 2d-array
m = np.array([[1, 2, 3],
			[2, 3, 4],
			[4, 5, 6]])

print("Printing the Original square array:\n",m)
print()
print('***************************************')
print()

Printing the Original square array:
 [[1 2 3]
 [2 3 4]
 [4 5 6]]

***************************************



In [ ]:
# finding eigenvalues and eigenvectors
w, v = np.linalg.eig(m)

In [ ]:
# printing eigen values
print("Printing the Eigen values of the given square array:\n",w)
print()

Printing the Eigen values of the given square array:
 [ 1.08309519e+01 -8.30951895e-01  1.01486082e-16]



In [ ]:
# printing eigen vectors
print("Printing Right eigenvectors of the given square array:\n",v)

Printing Right eigenvectors of the given square array:
 [[ 0.34416959  0.72770285  0.40824829]
 [ 0.49532111  0.27580256 -0.81649658]
 [ 0.79762415 -0.62799801  0.40824829]]


In [ ]:
import tensorflow as tf
# Let's see how we can compute the eigen vectors and values from a matrix

e_matrix_A = tf.random.uniform([2, 2], minval=3, maxval=10, dtype=tf.float32, name="matrixA")

print("Matrix A: \n{}\n\n".format(e_matrix_A))

Matrix A: 
[[7.5477686 9.690371 ]
 [3.0403204 9.128765 ]]




In [ ]:
# Calculating the eigen values and vectors using tf.linalg.eigh, if you only want the values you can use eigvalsh

eigen_values_A, eigen_vectors_A = tf.linalg.eigh(e_matrix_A)

print("Eigen Vectors: \n{} \n\nEigen Values: \n{}\n".format(eigen_vectors_A, eigen_values_A))

Eigen Vectors: 
[[-0.7910873 -0.6117031]
 [ 0.6117031 -0.7910873]] 

Eigen Values: 
[ 5.1968594 11.4796715]



In [ ]:
# Let's see how we can compute the eigen vectors and values from a matrix

e_matrix_A = tf.random.uniform([3, 3], minval=3, maxval=10, dtype=tf.float32, name="matrixA")

print("Matrix A: \n{}\n\n".format(e_matrix_A))

Matrix A: 
[[3.408463  7.607877  9.247894 ]
 [7.7837586 4.974331  6.1148043]
 [3.1414108 5.684109  6.246533 ]]




In [ ]:
# Calculating the eigen values and vectors using tf.linalg.eigh, if you only want the values you can use eigvalsh

eigen_values_A, eigen_vectors_A = tf.linalg.eigh(e_matrix_A)

print("Eigen Vectors: \n{} \n\nEigen Values: \n{}\n".format(eigen_vectors_A, eigen_values_A))

Eigen Vectors: 
[[-0.67557275  0.5103162   0.5321456 ]
 [ 0.7124913   0.26623726  0.64921045]
 [-0.18962568 -0.8177379   0.5434582 ]] 

Eigen Values: 
[-3.9189014  2.4354901 16.11274  ]

